### ISSUE TITLE
Crashes when I launch it

### ISSUE THREAD

**Issue by rayjlinden** [adaskar/AggregateVolumeMenu#3]
I'm on BigSur.  Last release looks like it just added support for Catalina.  Is this know to fail on BigSur?

I see it launch and add the speaker icon at the top of the screen.  However, when I click it - it just disappears.  I assume it is crashing...

**Comment by adaskar** [comment]
Actually it should still be working on BigSur as i'm using the latest one on my mac which is BigSur(11.2.3 (20D91)) as well. Can you please try to run it from the Terminal App. To open the app from terminal as i'm assuming you copied it to Applications, just write /Applications/AggregateVolumeMenu.app/Contents/MacOS/AggregateVolumeMenu.
What is the thing it has written to console before exiting itself?

**Comment by rayjlinden** [comment]
Just tried that.  It did not print much:
```
$  ./AggregateVolumeMenu
kAudioDevicePropertyVolumeScalar volLeft
```

Same behavior.  I click the icon - the icon disappeared, and this was printed.

**Comment by adaskar** [comment]
can you please share your Audio MIDI Setup screenshot? it should looks something like the below image.
<img width="648" alt="Screen Shot 2021-04-01 at 21 11 01" src="https://user-images.githubusercontent.com/2311537/113336243-c7839480-932e-11eb-813d-89e7b46d5975.png">

**Comment by thechriscrabb** [comment]
Can confirm I'm having the same issues here when connected to two iMacs via Target Display mode. Application launches and shows in menubar, but upon clicking, it crashes. Screenshot attached.
<img width="763" alt="Screen Shot 2021-04-02 at 2 53 05 PM" src="https://user-images.githubusercontent.com/27330327/113456874-40343080-93c3-11eb-816c-f9701edc189f.png">

**Comment by adaskar** [comment]
i have released 1.4 version of the app to get more error information, can you please run and share what you see in the console now?

**Comment by thechriscrabb** [comment]
Looks like it's just got the source code uploaded. Would you be able to upload the app itself?

**Comment by adaskar** [comment]
You can find the updated app in the releases tab

<img width="859" alt="Screen Shot 2021-04-05 at 08 17 00" src="https://user-images.githubusercontent.com/2311537/113539821-4c98d300-95e7-11eb-8290-f0523f9d55ee.png">

**Comment by thechriscrabb** [comment]
Maybe I’m an idiot and missing something here (likely), but when downloading and unzipping either of the two files shown, I’m only provided with the source code/Xcode project.

**Comment by adaskar** [comment]
Nope you are not but i’m the idiot one here for the case. I will upload the app when i get the chance. Sorry for that.

**Comment by adaskar** [comment]
I have uploaded the new version of the app (finally), so you can run now to get more information about the error you are facing

**Comment by rayjlinden** [comment]
Same crash, of course.  But here is the extra logging info:
```
rayj$ ./AggregateVolumeMenu
kAudioDevicePropertyVolumeScalar volLeft result:2003332927
```

**Comment by thechriscrabb** [comment]
Same outcome for me:

kAudioDevicePropertyVolumeScalar volLeft result:2003332927

**Comment by adaskar** [comment]
sorry for late update, i have uploaded a new release to obtain channel numbers from the coreaudio itself instead of using static numbers. can you please check that your problem persist or gone away? if the issue still persists, i may ask you the screenshot of the audio midi app when displayport 1 (or displayport 2) selected?

**Comment by thechriscrabb** [comment]
Issue seems to persist, unfortunately. The error I received in terminal is similar. I've tested with an aggregate device and a multi-output device:

`kAudioDevicePropertyVolumeScalar channel:1 result:2003332927`

![Screen Shot 2021-04-12 at 2 21 14 PM](https://user-images.githubusercontent.com/27330327/114464320-73807780-9b9a-11eb-90c1-477d2dae74d0.png)
![Screen Shot 2021-04-12 at 2 21 18 PM](https://user-images.githubusercontent.com/27330327/114464322-74190e00-9b9a-11eb-9a6c-7703668c04d3.png)

**Comment by adaskar** [comment]
I need the picture of the screen (Audio MIDI) when “DisplayPort 1” or “DisplayPort 2”. selected. Can you please provide that also?

**Comment by thechriscrabb** [comment]
Ahh, apologies. Attached below. Appreciate your hard work!

![22C617E8-3ADF-43C2-B879-762F84E8E498](https://user-images.githubusercontent.com/27330327/114563821-9ce5e580-9c24-11eb-8c94-b22bd4363334.jpeg)
![AD328F91-53F1-4F36-93B0-65ECE392159C](https://user-images.githubusercontent.com/27330327/114563825-9e171280-9c24-11eb-9bf5-54324774c367.jpeg)

**Comment by adaskar** [comment]
From my understanding, you even can not set those 2 channels inside “DisplayPort 1”, is it true?

**Comment by thechriscrabb** [comment]
That is correct. I am unable to adjust the volume for the devices connected via DisplayPort (iMacs using Target Display Mode) unless I connect a keyboard directly to either iMac and adjust the volume using the respective keyboard.

**Comment by adaskar** [comment]
if you can't change the volume using Audio MIDI Setup, you can't also change using this app. my thoughts are; it is something related with the os x itself, nothing can be done by an app. if you have some way to change the volume from the source of target display mode, i may help you but if not i will be considering that there is no way.

**Comment by rayjlinden** [comment]
In any case, your app should not crash!  :)

I’m not sure if my case is exactly the same.  I am using a Multi-Ouput
Device.  One is my LG screen the other is this software called Blackhole so
I could feed the desktop audio back into OBS when streaming.

I’ve read somewhere that when using multi-output you have to set the volume
on each device independently. You can not use the master volume of the
desktop.

Which is why I was looking at your control thing in the first place
actually.  However, it seems if the main device is not set able your
control just crashes.  So I never got to try it out further to see if it
would work for me.

Not sure if any of that blathering is helpful.  But is included on the off
chance it is!

**Comment by adaskar** [comment]
the reason app has been crashed (actually it is not a crash, it is a gracefully exit with the error code) on the cases like those is that someone can lose the volume synchronization between devices inside the Aggregate Device. 

I can make the app continue when the error code 2003332927 returned from os x functions, but you simply are going to face a situation like your main device volume will be changed but other devices inside the Aggregate Device (Display Port 1, Display Port 2) won't be changed at all.

So if you want, I can release an update but you again need to change volumes as you stated (like plugging keyboard, etc)

**Comment by thechriscrabb** [comment]
I kinda figured something like that may be the case. I’ll continue using the separate keyboards to adjust the volume. Thanks for clarifying and working with me on this.
