### ISSUE TITLE
App Crashes on macOS Big Sur Version 11.1 (20C69) when volume is changed

### ISSUE THREAD

**Issue by iKlancar** [adaskar/AggregateVolumeMenu#4]
As soon as I change the volume, the app crashed. 
![image](https://user-images.githubusercontent.com/3636871/130935059-53811ee1-4d21-4820-8653-3dff724bb108.png)

**Comment by adaskar** [comment]
Sorry for late answer, i have not been here for a while.
Can  you confirm that you have configured your aggregate sound device correctly?

**Comment by AJAYK-01** [comment]
> Sorry for late answer, i have not been here for a while.
> Can you confirm that you have configured your aggregate sound device correctly?

I'm getting a similar error while trying to build the app

<img width="471" alt="image" src="https://user-images.githubusercontent.com/55079486/134806834-9029d4d8-e188-48eb-906e-90d1449e4332.png">

**Comment by adaskar** [comment]
this app was designed to be used with aggregate sound device configured as 5.1 sound system.
if you don't have such configuration (both physical and software), this app is not going to work.
