### ISSUE TITLE
Doesn't seem to work with Big Sur 11.6

### ISSUE THREAD

**Issue by SchroedersKater** [adaskar/AggregateVolumeMenu#5]
On my system it shows it's icon on the menu bar, but as soon as I click on it, it disappears and the app is shut down.

BTW, I have BlackHole installed. I din't try without it. Should I?

**Comment by adaskar** [comment]
Yes you should try without it. By the way, can you please share your audio midi setup configuration by sending a screenshot?

**Comment by SystemDisc** [comment]
I am also experiencing this issue with BlackHole installed.

**Comment by SchroedersKater** [comment]
Sorry, I'm currently pretty busy, so I don't have the time for more tests. It will take a while.

**Comment by thewhitewayofdelight** [comment]
I'm also experiencing this issue!

**Comment by adaskar** [comment]
Can any of you share Audio Midi Setup configuration screen? This would make sense if the issue is related with configuration or app itself.

**Comment by TeoV00** [comment]
![image](https://user-images.githubusercontent.com/73893880/179457868-c597d5d2-2eaf-4c5b-a332-bfa28a4e331e.jpeg)

**Comment by moritzWa** [comment]
Same here 
![2022-09-12 09 26 34](https://user-images.githubusercontent.com/42035131/189596613-ed9d025c-afa5-435c-9eea-8e2ddaace9e6.gif)

**Comment by adaskar** [comment]
<img width="660" alt="Screen Shot 2022-09-12 at 21 52 18" src="https://user-images.githubusercontent.com/2311537/189733109-b9f24d71-794b-4c5b-bea7-be7fbaa19130.png">
your configuration should be look like that (5.1 config), any other config may not be working and this application is not indented to work with all aggregate configurations. but as you can see the source of the app is open, so you can change it for your needs.
