### ISSUE TITLE
App won't run in OSX Ventura

### ISSUE THREAD

**Issue by raafirivero** [adaskar/AggregateVolumeMenu#6]
Even after enabling it via system privacy settings in Ventura the app crashes whenever I attempt to raise or lower the volume with the keyboard. This sounds like the perfect app for my needs. I hope you're still working on it.

**Comment by adaskar** [comment]
sorry for my late, i'm not actively running this app but i can go with an helping hand.
this happened **only** while adjusting volume with keyboard, remaining functionality still going good, right?

**Comment by Blackspell01** [comment]
no it doesn't work at all, at least for me...

**Comment by adaskar** [comment]
sorry for my late answer, I was having troubles to find ventura running system.
i have installed and configured my audio channels using audio midi controller, and everything works flawlessly out of the box.
your configuration of aggregate device can be wrong i thought, i was attaching the one currently i'm using without a problem
<img width="648" alt="image" src="https://user-images.githubusercontent.com/2311537/227564549-41d64ec8-cba5-4e92-acb8-a8c43358521d.png">
